name: Generate Keystore
on: workflow_dispatch
jobs:
  keygen:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Key
        run: |
          keytool -genkey -v -keystore nexus.jks -keyalg RSA -keysize 2048 -validity 10000 -alias nexuskey -storepass nexus123 -keypass nexus123 -dname "CN=NexusQuiz, OU=Engineering, O=FUTA, L=Akure, S=Ondo, C=NG"
          echo "BASE64_KEY=$(base64 -w 0 nexus.jks)"
          keytool -list -v -keystore nexus.jks -alias nexuskey -storepass nexus123
